version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot

  nuxt:
    build:
      context: ./
      dockerfile: ./dockers/Dockerfile
    container_name: nuxt
    restart: always
    ports:
      - ${PORT}:${PORT}
    command:
      "npm run dev"
